// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mt.proto

package mt

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Target struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Target) Reset()         { *m = Target{} }
func (m *Target) String() string { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()    {}
func (*Target) Descriptor() ([]byte, []int) {
	return fileDescriptor_62ca348d81669599, []int{0}
}

func (m *Target) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Target.Unmarshal(m, b)
}
func (m *Target) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Target.Marshal(b, m, deterministic)
}
func (m *Target) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Target.Merge(m, src)
}
func (m *Target) XXX_Size() int {
	return xxx_messageInfo_Target.Size(m)
}
func (m *Target) XXX_DiscardUnknown() {
	xxx_messageInfo_Target.DiscardUnknown(m)
}

var xxx_messageInfo_Target proto.InternalMessageInfo

func (m *Target) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type ListTargetResponse struct {
	Targets              []*Target `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListTargetResponse) Reset()         { *m = ListTargetResponse{} }
func (m *ListTargetResponse) String() string { return proto.CompactTextString(m) }
func (*ListTargetResponse) ProtoMessage()    {}
func (*ListTargetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62ca348d81669599, []int{1}
}

func (m *ListTargetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTargetResponse.Unmarshal(m, b)
}
func (m *ListTargetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTargetResponse.Marshal(b, m, deterministic)
}
func (m *ListTargetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTargetResponse.Merge(m, src)
}
func (m *ListTargetResponse) XXX_Size() int {
	return xxx_messageInfo_ListTargetResponse.Size(m)
}
func (m *ListTargetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTargetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTargetResponse proto.InternalMessageInfo

func (m *ListTargetResponse) GetTargets() []*Target {
	if m != nil {
		return m.Targets
	}
	return nil
}

type ListTargetParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTargetParams) Reset()         { *m = ListTargetParams{} }
func (m *ListTargetParams) String() string { return proto.CompactTextString(m) }
func (*ListTargetParams) ProtoMessage()    {}
func (*ListTargetParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_62ca348d81669599, []int{2}
}

func (m *ListTargetParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTargetParams.Unmarshal(m, b)
}
func (m *ListTargetParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTargetParams.Marshal(b, m, deterministic)
}
func (m *ListTargetParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTargetParams.Merge(m, src)
}
func (m *ListTargetParams) XXX_Size() int {
	return xxx_messageInfo_ListTargetParams.Size(m)
}
func (m *ListTargetParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTargetParams.DiscardUnknown(m)
}

var xxx_messageInfo_ListTargetParams proto.InternalMessageInfo

type NewTargetParams struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTargetParams) Reset()         { *m = NewTargetParams{} }
func (m *NewTargetParams) String() string { return proto.CompactTextString(m) }
func (*NewTargetParams) ProtoMessage()    {}
func (*NewTargetParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_62ca348d81669599, []int{3}
}

func (m *NewTargetParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTargetParams.Unmarshal(m, b)
}
func (m *NewTargetParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTargetParams.Marshal(b, m, deterministic)
}
func (m *NewTargetParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTargetParams.Merge(m, src)
}
func (m *NewTargetParams) XXX_Size() int {
	return xxx_messageInfo_NewTargetParams.Size(m)
}
func (m *NewTargetParams) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTargetParams.DiscardUnknown(m)
}

var xxx_messageInfo_NewTargetParams proto.InternalMessageInfo

func (m *NewTargetParams) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type NewTargetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTargetResponse) Reset()         { *m = NewTargetResponse{} }
func (m *NewTargetResponse) String() string { return proto.CompactTextString(m) }
func (*NewTargetResponse) ProtoMessage()    {}
func (*NewTargetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62ca348d81669599, []int{4}
}

func (m *NewTargetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTargetResponse.Unmarshal(m, b)
}
func (m *NewTargetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTargetResponse.Marshal(b, m, deterministic)
}
func (m *NewTargetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTargetResponse.Merge(m, src)
}
func (m *NewTargetResponse) XXX_Size() int {
	return xxx_messageInfo_NewTargetResponse.Size(m)
}
func (m *NewTargetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTargetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewTargetResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Target)(nil), "mt.Target")
	proto.RegisterType((*ListTargetResponse)(nil), "mt.ListTargetResponse")
	proto.RegisterType((*ListTargetParams)(nil), "mt.ListTargetParams")
	proto.RegisterType((*NewTargetParams)(nil), "mt.NewTargetParams")
	proto.RegisterType((*NewTargetResponse)(nil), "mt.NewTargetResponse")
}

func init() { proto.RegisterFile("mt.proto", fileDescriptor_62ca348d81669599) }

var fileDescriptor_62ca348d81669599 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xc8, 0x2d, 0xd1, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xca, 0x2d, 0x51, 0x92, 0xe1, 0x62, 0x0b, 0x49, 0x2c, 0x4a,
	0x4f, 0x2d, 0x11, 0x12, 0xe2, 0x62, 0x49, 0x4c, 0x49, 0x29, 0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0c, 0x02, 0xb3, 0x95, 0xac, 0xb8, 0x84, 0x7c, 0x32, 0x8b, 0x4b, 0x20, 0x2a, 0x82, 0x52, 0x8b,
	0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x54, 0xb8, 0xd8, 0x4b, 0xc0, 0x22, 0xc5, 0x40, 0xc5, 0xcc,
	0x1a, 0xdc, 0x46, 0x5c, 0x7a, 0x40, 0x33, 0xa1, 0x8a, 0x60, 0x52, 0x4a, 0x42, 0x5c, 0x02, 0x08,
	0xbd, 0x01, 0x89, 0x45, 0x89, 0xb9, 0xc5, 0x4a, 0xaa, 0x5c, 0xfc, 0x7e, 0xa9, 0xe5, 0xc8, 0x42,
	0x58, 0xad, 0x15, 0xe6, 0x12, 0x84, 0x2b, 0x83, 0xd9, 0x6a, 0x54, 0xc6, 0xc5, 0x0e, 0x11, 0x29,
	0x16, 0x32, 0xe3, 0x62, 0x01, 0x19, 0x2d, 0x24, 0x02, 0xb2, 0x17, 0xdd, 0x12, 0x29, 0x31, 0x54,
	0x51, 0x98, 0x01, 0x4a, 0x0c, 0x42, 0xc6, 0x5c, 0xcc, 0x40, 0x73, 0x85, 0x84, 0x41, 0x0a, 0xd0,
	0xdc, 0x21, 0x25, 0x8a, 0x22, 0x88, 0xd0, 0x94, 0xc4, 0x06, 0x0e, 0x2c, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x70, 0xe7, 0xae, 0x4e, 0x38, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TargetsClient is the client API for Targets service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TargetsClient interface {
	List(ctx context.Context, in *ListTargetParams, opts ...grpc.CallOption) (*ListTargetResponse, error)
	New(ctx context.Context, in *NewTargetParams, opts ...grpc.CallOption) (*NewTargetResponse, error)
}

type targetsClient struct {
	cc *grpc.ClientConn
}

func NewTargetsClient(cc *grpc.ClientConn) TargetsClient {
	return &targetsClient{cc}
}

func (c *targetsClient) List(ctx context.Context, in *ListTargetParams, opts ...grpc.CallOption) (*ListTargetResponse, error) {
	out := new(ListTargetResponse)
	err := c.cc.Invoke(ctx, "/mt.Targets/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetsClient) New(ctx context.Context, in *NewTargetParams, opts ...grpc.CallOption) (*NewTargetResponse, error) {
	out := new(NewTargetResponse)
	err := c.cc.Invoke(ctx, "/mt.Targets/New", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TargetsServer is the server API for Targets service.
type TargetsServer interface {
	List(context.Context, *ListTargetParams) (*ListTargetResponse, error)
	New(context.Context, *NewTargetParams) (*NewTargetResponse, error)
}

// UnimplementedTargetsServer can be embedded to have forward compatible implementations.
type UnimplementedTargetsServer struct {
}

func (*UnimplementedTargetsServer) List(ctx context.Context, req *ListTargetParams) (*ListTargetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedTargetsServer) New(ctx context.Context, req *NewTargetParams) (*NewTargetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method New not implemented")
}

func RegisterTargetsServer(s *grpc.Server, srv TargetsServer) {
	s.RegisterService(&_Targets_serviceDesc, srv)
}

func _Targets_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTargetParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt.Targets/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetsServer).List(ctx, req.(*ListTargetParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Targets_New_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTargetParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetsServer).New(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt.Targets/New",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetsServer).New(ctx, req.(*NewTargetParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _Targets_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mt.Targets",
	HandlerType: (*TargetsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Targets_List_Handler,
		},
		{
			MethodName: "New",
			Handler:    _Targets_New_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mt.proto",
}
